version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    allow:
      # we don't care about transitive dependencies since this is just a placeholder so we can update vercel.json
      - dependency-name: "vercel-rust"
