on: [push]
name: CI
jobs:
  build-and-lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy -- -D warnings
