on: [pull_request]
name: "cargo update"
# required for dependabot to be able to commit changes
permissions:
  contents: write
jobs:
  cargo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      - name: Check if Cargo.toml or rust-toolchain changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            package:
              - Cargo.toml
              - rust-toolchain.toml
      - name: cargo update
        if: steps.changed-files-yaml.outputs.package_any_changed == 'true'
        run: cargo update
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "update Cargo.lock"
          push: true
